### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/sphone#4]
1) use cache for this section
![image](https://user-images.githubusercontent.com/19146254/45974285-62160500-c05a-11e8-8ac5-2e280d04ca37.png)
right now its coming direct from DB

**Comment by serviceproviderpk** [comment]
2) 
![image](https://user-images.githubusercontent.com/19146254/45974380-9b4e7500-c05a-11e8-9522-f353ffbb073c.png)
also show from cache
it will show products from product table whose views are much.
use select {PId,Catid,subcatid,Title of product only instead of all fields}
i can explain it.

**Comment by serviceproviderpk** [comment]
3) if search product by price like http://localhost:56547/501_to_1000_mobile

footer is total zig zag
![image](https://user-images.githubusercontent.com/19146254/45974971-59bec980-c05c-11e8-9844-d92203adb5ef.png)

**Comment by serviceproviderpk** [comment]
4) for paging use proper css
![image](https://user-images.githubusercontent.com/19146254/45975005-7b1fb580-c05c-11e8-9ea1-9f9e599d2592.png)

use two color instead of 3 color ( White+Gray  OR white + green)

**Comment by serviceproviderpk** [comment]
5)remove below section from all pages
![image](https://user-images.githubusercontent.com/19146254/45975088-b621e900-c05c-11e8-9d05-7aeff1363141.png)

**Comment by serviceproviderpk** [comment]
6) news detail page is looking distrubed
http://saudi-phone.com/news/more-pixel-3-and-pixel-3-xl-images-appear-ahead-of-their-october-launch-601537

**Comment by zaifullah786** [comment]
(1,2,3,5)RFR
